# SPDX-FileCopyrightText: 2026 SPDX contributors
# SPDX-FileContributor: SPDX AI Working Group and its Contributors
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0

name: Markdown Lint

on:
  push:
    paths: ['**/*.md']
  pull_request:
    paths: ['**/*.md']

jobs:
  markdownlint:
    name: Run Markdown lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            **/*.md
            !License.md
